
ALTER TABLE public.publijus_config
  ADD COLUMN IF NOT EXISTS lista_path TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS map_cnj TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS map_data TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS map_descricao TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS map_id TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS map_orgao TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS map_tipo TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS exemplo_json TEXT;
